commenters = [
                {'user_id': 4941374523, 'username': 'aly_mckae', 'text': 'This is why you=great president'},
                {'user_id': 5637957450, 'username': 'roberto_torrero_reyes', 'text': '👏👏👏👏👏👏👏👏 yes'},
                {'user_id': 1578221754, 'username': 'alleniumfalcon_', 'text': '@taichi_x.o nah man life is good your mom makes me the happiest man alive the way she put it down.'},
                {'user_id': 6498284351, 'username': 'gulshat.916', 'text': '👍😍✊'},
                {'user_id': 1639894744, 'username': 'judymacish', 'text': 'I love you and Michelle!  You both are so admirable and lovable.'},
                {'user_id': 1929719901, 'username': 'taichi_x.o', 'text': '@alleniumfalcon_ nooo problem buddy. Come back for me. I know how hard life is for you rn. 😂😂'},
                {'user_id': 12277833216, 'username': 'christina.masden', 'text': 'No, n****, you dont get to use my name. Every person in this photo needs a reality check. Go meet w uganda'},
                {'user_id': 4560294226, 'username': 's.gholipour67', 'text': 'Down with trump and the god bless you'},
                {'user_id': 9469099061, 'username': 'mhmd.aziz90', 'text': 'im from lebanon luv uu'},
                {'user_id': 3935406510, 'username': 'kameelahays1248', 'text': 'You are their inspiration😍'},
                {'user_id': 10987073459, 'username': 'svenkummelt', 'text': '👏'},
                {'user_id': 6817075592, 'username': 'rocco_dimatteo1', 'text': '@taichi_x.o what political leader do u support.'},
                {'user_id': 1578221754, 'username': 'alleniumfalcon_', 'text': '@taichi_x.o its delicious tell your mom i said thanks.'},
                {'user_id': 4024270435, 'username': 'dianavincaa', 'text': "Let's make America great again!🙏🙌❤️"},
                {'user_id': 8151522693, 'username': 'ahmadhassni7038', 'text': 'اوباما یادته خائن من و موعود چه بر سرت آوردیم  تو با هم دستی اسرائیل و هزینه ترکیه قطر و سعودی آن لشکر رو ساختی یادته سلطان رو'},
                {'user_id': 12379237358, 'username': 'commanderindia', 'text': 'Tjen i surely need u🔥❤️😎'},
                {'user_id': 11951659356, 'username': '815_myn', 'text': 'باو بوخره'},
                {'user_id': 12588939, 'username': 'danaberch', 'text': 'Yes 🙌🙌🙌🙌'},
                {'user_id': 8306029349, 'username': 'steve_florist_realtor_morgan', 'text': '@taichi_x.o Self pity has nothing to do with wealth.. Trump is proof of that.. thanks for proving my point..'},
                {'user_id': 4941374523, 'username': 'aly_mckae', 'text': 'This is why you=great president'},
                {'user_id': 5637957450, 'username': 'roberto_torrero_reyes', 'text': '👏👏👏👏👏👏👏👏 yes'},
                {'user_id': 1578221754, 'username': 'alleniumfalcon_', 'text': '@taichi_x.o nah man life is good your mom makes me the happiest man alive the way she put it down.'},
                {'user_id': 6498284351, 'username': 'gulshat.916', 'text': '👍😍✊'},
                {'user_id': 1639894744, 'username': 'judymacish', 'text': 'I love you and Michelle!  You both are so admirable and lovable.'},
                {'user_id': 1929719901, 'username': 'taichi_x.o', 'text': '@alleniumfalcon_ nooo problem buddy. Come back for me. I know how hard life is for you rn. 😂😂'},
                {'user_id': 12277833216, 'username': 'christina.masden', 'text': 'No, n****, you dont get to use my name. Every person in this photo needs a reality check. Go meet w uganda'},
                {'user_id': 4560294226, 'username': 's.gholipour67', 'text': 'Down with trump and the god bless you'},
                {'user_id': 9469099061, 'username': 'mhmd.aziz90', 'text': 'im from lebanon luv uu'},
                {'user_id': 3935406510, 'username': 'kameelahays1248', 'text': 'You are their inspiration😍'},
                {'user_id': 10987073459, 'username': 'svenkummelt', 'text': '👏'},
                {'user_id': 6817075592, 'username': 'rocco_dimatteo1', 'text': '@taichi_x.o what political leader do u support.'},
                {'user_id': 1578221754, 'username': 'alleniumfalcon_', 'text': '@taichi_x.o its delicious tell your mom i said thanks.'},
                {'user_id': 4024270435, 'username': 'dianavincaa', 'text': "Let's make America great again!🙏🙌❤️"},
                {'user_id': 8151522693, 'username': 'ahmadhassni7038', 'text': 'اوباما یادته خائن من و موعود چه بر سرت آوردیم  تو با هم دستی اسرائیل و هزینه ترکیه قطر و سعودی آن لشکر رو ساختی یادته سلطان رو'},
                {'user_id': 12379237358, 'username': 'commanderindia', 'text': 'Tjen i surely need u🔥❤️😎'},
                {'user_id': 11951659356, 'username': '815_myn', 'text': 'باو بوخره'},
                {'user_id': 12588939, 'username': 'danaberch', 'text': 'Yes 🙌🙌🙌🙌'},
                {'user_id': 8306029349, 'username': 'steve_florist_realtor_morgan', 'text': '@taichi_x.o Self pity has nothing to do with wealth.. Trump is proof of that.. thanks for proving my point..'},
                {'user_id': 1423821880, 'username': 'dduchessny', 'text': 'Good for that girl for wearing sneakers!'},
                {'user_id': 4941374523, 'username': 'aly_mckae', 'text': 'This is why you=great president'},
                {'user_id': 5637957450, 'username': 'roberto_torrero_reyes', 'text': '👏👏👏👏👏👏👏👏 yes'},
                {'user_id': 1578221754, 'username': 'alleniumfalcon_', 'text': '@taichi_x.o nah man life is good your mom makes me the happiest man alive the way she put it down.'},
                {'user_id': 6498284351, 'username': 'gulshat.916', 'text': '👍😍✊'}, {'user_id': 1639894744, 'username': 'judymacish', 'text': 'I love you and Michelle!  You both are so admirable and lovable.'}, {'user_id': 1929719901, 'username': 'taichi_x.o', 'text': '@alleniumfalcon_ nooo problem buddy. Come back for me. I know how hard life is for you rn. 😂😂'},
                {'user_id': 12277833216, 'username': 'christina.masden', 'text': 'No, n****, you dont get to use my name. Every person in this photo needs a reality check. Go meet w uganda'},
                {'user_id': 4560294226, 'username': 's.gholipour67', 'text': 'Down with trump and the god bless you'},
                {'user_id': 9469099061, 'username': 'mhmd.aziz90', 'text': 'im from lebanon luv uu'},
                {'user_id': 3935406510, 'username': 'kameelahays1248', 'text': 'You are their inspiration😍'},
                {'user_id': 10987073459, 'username': 'svenkummelt', 'text': '👏'},
                {'user_id': 6817075592, 'username': 'rocco_dimatteo1', 'text': '@taichi_x.o what political leader do u support.'},
                {'user_id': 1578221754, 'username': 'alleniumfalcon_', 'text': '@taichi_x.o its delicious tell your mom i said thanks.'},
                {'user_id': 4024270435, 'username': 'dianavincaa', 'text': "Let's make America great again!🙏🙌❤️"},
                {'user_id': 8151522693, 'username': 'ahmadhassni7038', 'text': 'اوباما یادته خائن من و موعود چه بر سرت آوردیم  تو با هم دستی اسرائیل و هزینه ترکیه قطر و سعودی آن لشکر رو ساختی یادته سلطان رو'},
                {'user_id': 12379237358, 'username': 'commanderindia', 'text': 'Tjen i surely need u🔥❤️😎'},
                {'user_id': 11951659356, 'username': '815_myn', 'text': 'باو بوخره'},
                {'user_id': 12588939, 'username': 'danaberch', 'text': 'Yes 🙌🙌🙌🙌'},
                {'user_id': 1423821880, 'username': 'dduchessny', 'text': 'Good for that girl for wearing sneakers!'},
                {'user_id': 4941374523, 'username': 'aly_mckae', 'text': 'This is why you=great president'},
                {'user_id': 5637957450, 'username': 'roberto_torrero_reyes', 'text': '👏👏👏👏👏👏👏👏 yes'},
                {'user_id': 1578221754, 'username': 'alleniumfalcon_', 'text': '@taichi_x.o nah man life is good your mom makes me the happiest man alive the way she put it down.'},
                {'user_id': 6498284351, 'username': 'gulshat.916', 'text': '👍😍✊'},
                {'user_id': 1639894744, 'username': 'judymacish', 'text': 'I love you and Michelle!  You both are so admirable and lovable.'},
                {'user_id': 1929719901, 'username': 'taichi_x.o', 'text': '@alleniumfalcon_ nooo problem buddy. Come back for me. I know how hard life is for you rn. 😂😂'},
                {'user_id': 12277833216, 'username': 'christina.masden', 'text': 'No, n****, you dont get to use my name. Every person in this photo needs a reality check. Go meet w uganda'},
                {'user_id': 4560294226, 'username': 's.gholipour67', 'text': 'Down with trump and the god bless you'},
                {'user_id': 9469099061, 'username': 'mhmd.aziz90', 'text': 'im from lebanon luv uu'},
                {'user_id': 3935406510, 'username': 'kameelahays1248', 'text': 'You are their inspiration😍'},
                {'user_id': 10987073459, 'username': 'svenkummelt', 'text': '👏'},
                {'user_id': 6817075592, 'username': 'rocco_dimatteo1', 'text': '@taichi_x.o what political leader do u support.'},
                {'user_id': 1578221754, 'username': 'alleniumfalcon_', 'text': '@taichi_x.o its delicious tell your mom i said thanks.'},
                {'user_id': 4024270435, 'username': 'dianavincaa', 'text': "Let's make America great again!🙏🙌❤️"},
                {'user_id': 8151522693, 'username': 'ahmadhassni7038', 'text': 'اوباما یادته خائن من و موعود چه بر سرت آوردیم  تو با هم دستی اسرائیل و هزینه ترکیه قطر و سعودی آن لشکر رو ساختی یادته سلطان رو'},
                {'user_id': 12379237358, 'username': 'commanderindia', 'text': 'Tjen i surely need u🔥❤️😎'}, {'user_id': 11951659356, 'username': '815_myn', 'text': 'باو بوخره'}, {'user_id': 12588939, 'username': 'danaberch', 'text': 'Yes 🙌🙌🙌🙌'}, {'user_id': 1423821880, 'username': 'dduchessny', 'text': 'Good for that girl for wearing sneakers!'}, {'user_id': 4941374523, 'username': 'aly_mckae', 'text': 'This is why you=great president'}, {'user_id': 5637957450, 'username': 'roberto_torrero_reyes', 'text': '👏👏👏👏👏👏👏👏 yes'},
                {'user_id': 1578221754, 'username': 'alleniumfalcon_', 'text': '@taichi_x.o nah man life is good your mom makes me the happiest man alive the way she put it down.'},
                {'user_id': 6498284351, 'username': 'gulshat.916', 'text': '👍😍✊'},
                {'user_id': 1639894744, 'username': 'judymacish', 'text': 'I love you and Michelle!  You both are so admirable and lovable.'},
                {'user_id': 1929719901, 'username': 'taichi_x.o', 'text': '@alleniumfalcon_ nooo problem buddy. Come back for me. I know how hard life is for you rn. 😂😂'},
                {'user_id': 12277833216, 'username': 'christina.masden', 'text': 'No, n****, you dont get to use my name. Every person in this photo needs a reality check. Go meet w uganda'},
                {'user_id': 4560294226, 'username': 's.gholipour67', 'text': 'Down with trump and the god bless you'},
                {'user_id': 9469099061, 'username': 'mhmd.aziz90', 'text': 'im from lebanon luv uu'},
                {'user_id': 3935406510, 'username': 'kameelahays1248', 'text': 'You are their inspiration😍'},
                {'user_id': 10987073459, 'username': 'svenkummelt', 'text': '👏'},
                {'user_id': 6817075592, 'username': 'rocco_dimatteo1', 'text': '@taichi_x.o what political leader do u support.'},
                {'user_id': 1578221754, 'username': 'alleniumfalcon_', 'text': '@taichi_x.o its delicious tell your mom i said thanks.'},
                {'user_id': 4024270435, 'username': 'dianavincaa', 'text': "Let's make America great again!🙏🙌❤️"},
                {'user_id': 8151522693, 'username': 'ahmadhassni7038', 'text': 'اوباما یادته خائن من و موعود چه بر سرت آوردیم  تو با هم دستی اسرائیل و هزینه ترکیه قطر و سعودی آن لشکر رو ساختی یادته سلطان رو'},
                {'user_id': 12379237358, 'username': 'commanderindia', 'text': 'Tjen i surely need u🔥❤️😎'},
                {'user_id': 11951659356, 'username': '815_myn', 'text': 'باو بوخره'},
                {'user_id': 12588939, 'username': 'danaberch', 'text': 'Yes 🙌🙌🙌🙌'},
                {'user_id': 1423821880, 'username': 'dduchessny', 'text': 'Good for that girl for wearing sneakers!'},
                {'user_id': 4941374523, 'username': 'aly_mckae', 'text': 'This is why you=great president'},
                {'user_id': 5637957450, 'username': 'roberto_torrero_reyes', 'text': '👏👏👏👏👏👏👏👏 yes'},
                {'user_id': 1578221754, 'username': 'alleniumfalcon_', 'text': '@taichi_x.o nah man life is good your mom makes me the happiest man alive the way she put it down.'},
                {'user_id': 6498284351, 'username': 'gulshat.916', 'text': '👍😍✊'}
            ]
